### ISSUE TITLE
Problem with Working Directory?

### ISSUE THREAD

**Issue by Casper042** [ImperialPlugins/unturned-docker#2]
Tried to load this tonight and getting some errors while loading:
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: wrong ELF class: ELFCLASS32
[S_API FAIL] SteamAPI_Init(): Sys_LoadModule failed to load: steamclient.so

I traced back to init.sh trying to copy steamclient.so and failing.

This seems to be because init.sh is running from /opt/steamcmd
However the linux64 + Unturned Headless folders only exist together at the same level in:
/home/steam/Unturned

So it feels like the PWD is wrong somewhere along the lines or one of your dependencies moved something.
Is something you can easily fix?

I'm no Docker Guru, but was just chasing the logs and digging around inside the container's folder structure.
If someone else has a Unturned container you would recommend, happy to take another look.  But ramdad's server also looks pretty stale and they don't offer a Dedicated Server option (you must provide Steam Creds)

**Comment by Trojaner** [comment]
This image is currently outdated

**Comment by jvanlangen** [comment]
But it is still an issue.

```
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: wrong ELF class: ELFCLASS32
dlopen failed trying to load:
/home/steam/.steam/sdk64/steamclient.so
with error:
/home/steam/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/steam/.steam/sdk64/steamclient.so
```

**Comment by dvdblk** [comment]
Same issue here.

```
Linking spawns...
Loading miscellaneous...
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: wrong ELF class: ELFCLASS32
dlopen failed trying to load:
/home/steam/.steam/sdk64/steamclient.so
with error:
/home/steam/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/steam/.steam/sdk64/steamclient.so
Setting up 1 worker threads for Enlighten.
  Thread -> id: 7f7322a4f700 -> priority: 1 
```

**Comment by dvdblk** [comment]
I've fixed it by changing the paths in `init.sh`. Will post PR soon.
